[project]
name = "wiki-migrate"
version = "0.1.0"
description = "A tool to migrate a DokuWiki installation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "click",
  "toml",
  "pydantic",
  "requests",
  "beautifulsoup4"
]
