# Generated by ariadne-codegen
# Source: migrator/wikijs/queries.graphql

from typing import Any, Dict, List, Optional, Union

from .base_client import BaseClient
from .base_model import UNSET, UnsetType
from .create_folder import CreateFolder
from .create_page import CreatePage
from .delete_page import DeletePage
from .list_folders import ListFolders
from .list_pages import ListPages
from .update_page import UpdatePage


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def create_page(
        self,
        content: str,
        description: str,
        is_published: bool,
        is_private: bool,
        editor: str,
        locale: str,
        path: str,
        title: str,
        tags: List[str],
        **kwargs: Any
    ) -> CreatePage:
        query = gql(
            """
            mutation CreatePage($content: String!, $description: String!, $isPublished: Boolean!, $isPrivate: Boolean!, $editor: String!, $locale: String!, $path: String!, $title: String!, $tags: [String]!) {
              pages {
                create(
                  content: $content
                  description: $description
                  isPublished: $isPublished
                  isPrivate: $isPrivate
                  title: $title
                  editor: $editor
                  path: $path
                  locale: $locale
                  tags: $tags
                ) {
                  responseResult {
                    succeeded
                    errorCode
                    slug
                    message
                  }
                  page {
                    id
                    path
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "content": content,
            "description": description,
            "isPublished": is_published,
            "isPrivate": is_private,
            "editor": editor,
            "locale": locale,
            "path": path,
            "title": title,
            "tags": tags,
        }
        response = self.execute(
            query=query, operation_name="CreatePage", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreatePage.model_validate(data)

    def update_page(
        self, id: int, content: str, editor: str, tags: List[str], **kwargs: Any
    ) -> UpdatePage:
        query = gql(
            """
            mutation UpdatePage($id: Int!, $content: String!, $editor: String!, $tags: [String!]!) {
              pages {
                update(id: $id, content: $content, editor: $editor, tags: $tags) {
                  responseResult {
                    succeeded
                    errorCode
                    slug
                    message
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "id": id,
            "content": content,
            "editor": editor,
            "tags": tags,
        }
        response = self.execute(
            query=query, operation_name="UpdatePage", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return UpdatePage.model_validate(data)

    def create_folder(
        self,
        parent_folder_id: int,
        slug: str,
        name: Union[Optional[str], UnsetType] = UNSET,
        **kwargs: Any
    ) -> CreateFolder:
        query = gql(
            """
            mutation CreateFolder($parentFolderId: Int!, $slug: String!, $name: String) {
              assets {
                createFolder(parentFolderId: $parentFolderId, slug: $slug, name: $name) {
                  responseResult {
                    succeeded
                    errorCode
                    slug
                    message
                  }
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {
            "parentFolderId": parent_folder_id,
            "slug": slug,
            "name": name,
        }
        response = self.execute(
            query=query, operation_name="CreateFolder", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CreateFolder.model_validate(data)

    def list_folders(self, parent_folder_id: int, **kwargs: Any) -> ListFolders:
        query = gql(
            """
            query ListFolders($parentFolderId: Int!) {
              assets {
                folders(parentFolderId: $parentFolderId) {
                  id
                  slug
                  name
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"parentFolderId": parent_folder_id}
        response = self.execute(
            query=query, operation_name="ListFolders", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListFolders.model_validate(data)

    def list_pages(self, **kwargs: Any) -> ListPages:
        query = gql(
            """
            query ListPages {
              pages {
                list {
                  id
                  path
                  locale
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(
            query=query, operation_name="ListPages", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ListPages.model_validate(data)

    def delete_page(self, page_id: int, **kwargs: Any) -> DeletePage:
        query = gql(
            """
            mutation DeletePage($pageId: Int!) {
              pages {
                delete(id: $pageId) {
                  responseResult {
                    ...FullResponseResult
                  }
                }
              }
            }

            fragment FullResponseResult on ResponseStatus {
              succeeded
              errorCode
              slug
              message
            }
            """
        )
        variables: Dict[str, object] = {"pageId": page_id}
        response = self.execute(
            query=query, operation_name="DeletePage", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return DeletePage.model_validate(data)
