# Generated by ariadne-codegen
# Source: migrator/wikijs/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreateFolder(BaseModel):
    assets: Optional["CreateFolderAssets"]


class CreateFolderAssets(BaseModel):
    create_folder: Optional["CreateFolderAssetsCreateFolder"] = Field(
        alias="createFolder"
    )


class CreateFolderAssetsCreateFolder(BaseModel):
    response_result: Optional["CreateFolderAssetsCreateFolderResponseResult"] = Field(
        alias="responseResult"
    )


class CreateFolderAssetsCreateFolderResponseResult(BaseModel):
    succeeded: bool
    error_code: int = Field(alias="errorCode")
    slug: str
    message: Optional[str]


CreateFolder.model_rebuild()
CreateFolderAssets.model_rebuild()
CreateFolderAssetsCreateFolder.model_rebuild()
