# Generated by ariadne-codegen
# Source: migrator/wikijs/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class CreatePage(BaseModel):
    pages: Optional["CreatePagePages"]


class CreatePagePages(BaseModel):
    create: Optional["CreatePagePagesCreate"]


class CreatePagePagesCreate(BaseModel):
    response_result: "CreatePagePagesCreateResponseResult" = Field(
        alias="responseResult"
    )
    page: Optional["CreatePagePagesCreatePage"]


class CreatePagePagesCreateResponseResult(BaseModel):
    succeeded: bool
    error_code: int = Field(alias="errorCode")
    slug: str
    message: Optional[str]


class CreatePagePagesCreatePage(BaseModel):
    id: int
    path: str


CreatePage.model_rebuild()
CreatePagePages.model_rebuild()
CreatePagePagesCreate.model_rebuild()
