# Generated by ariadne-codegen
# Source: migrator/wikijs/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .fragments import FullResponseResult


class DeletePage(BaseModel):
    pages: Optional["DeletePagePages"]


class DeletePagePages(BaseModel):
    delete: Optional["DeletePagePagesDelete"]


class DeletePagePagesDelete(BaseModel):
    response_result: Optional["DeletePagePagesDeleteResponseResult"] = Field(
        alias="responseResult"
    )


class DeletePagePagesDeleteResponseResult(FullResponseResult):
    pass


DeletePage.model_rebuild()
DeletePagePages.model_rebuild()
DeletePagePagesDelete.model_rebuild()
