# Generated by ariadne-codegen
# Source: migrator/wikijs/schema.graphql

from enum import Enum


class AssetKind(str, Enum):
    IMAGE = "IMAGE"
    BINARY = "BINARY"
    ALL = "ALL"


class PageRuleMatch(str, Enum):
    START = "START"
    EXACT = "EXACT"
    END = "END"
    REGEX = "REGEX"
    TAG = "TAG"


class NavigationMode(str, Enum):
    NONE = "NONE"
    TREE = "TREE"
    MIXED = "MIXED"
    STATIC = "STATIC"


class PageOrderBy(str, Enum):
    CREATED = "CREATED"
    ID = "ID"
    PATH = "PATH"
    TITLE = "TITLE"
    UPDATED = "UPDATED"


class PageOrderByDirection(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class PageTreeMode(str, Enum):
    FOLDERS = "FOLDERS"
    PAGES = "PAGES"
    ALL = "ALL"


class SystemImportUsersGroupMode(str, Enum):
    MULTI = "MULTI"
    SINGLE = "SINGLE"
    NONE = "NONE"


class CacheControlScope(str, Enum):
    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
