# Generated by ariadne-codegen
# Source: migrator/wikijs/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class FullResponseResult(BaseModel):
    succeeded: bool
    error_code: int = Field(alias="errorCode")
    slug: str
    message: Optional[str]


FullResponseResult.model_rebuild()
