# Generated by ariadne-codegen
# Source: migrator/wikijs/queries.graphql

from typing import List, Optional

from .base_model import BaseModel


class ListFolders(BaseModel):
    assets: Optional["ListFoldersAssets"]


class ListFoldersAssets(BaseModel):
    folders: Optional[List[Optional["ListFoldersAssetsFolders"]]]


class ListFoldersAssetsFolders(BaseModel):
    id: int
    slug: str
    name: Optional[str]


ListFolders.model_rebuild()
ListFoldersAssets.model_rebuild()
