# Generated by ariadne-codegen
# Source: migrator/wikijs/queries.graphql

from typing import List, Optional

from .base_model import BaseModel


class ListPages(BaseModel):
    pages: Optional["ListPagesPages"]


class ListPagesPages(BaseModel):
    list: List["ListPagesPagesList"]


class ListPagesPagesList(BaseModel):
    id: int
    path: str
    locale: str


ListPages.model_rebuild()
ListPagesPages.model_rebuild()
