# Generated by ariadne-codegen
# Source: migrator/wikijs/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdatePage(BaseModel):
    pages: Optional["UpdatePagePages"]


class UpdatePagePages(BaseModel):
    update: Optional["UpdatePagePagesUpdate"]


class UpdatePagePagesUpdate(BaseModel):
    response_result: "UpdatePagePagesUpdateResponseResult" = Field(
        alias="responseResult"
    )


class UpdatePagePagesUpdateResponseResult(BaseModel):
    succeeded: bool
    error_code: int = Field(alias="errorCode")
    slug: str
    message: Optional[str]


UpdatePage.model_rebuild()
UpdatePagePages.model_rebuild()
UpdatePagePagesUpdate.model_rebuild()
